# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4192358454fd4b0cc5344e2c525e147059c920927bce19771e7dd8937b7ad5e167a2939aae4c68484410d4129df640f242ba4ef013ef51ec0bb9e248961a08ad

test:
  secret_key_base: d7c8738b20aa270622f36fd54d788e641d4d9b7c6178bdd7ec053f3039a3dd71440ce01438e48d68cf8729d21291e22fcc9948aef60fffbe2df35644fa477ca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
